### ISSUE TITLE
Error building _augeas.c, 'AUG_ENABLE_SPAN' undeclared

### ISSUE THREAD

**Issue by overnin** [lutter/ruby-augeas-unused#4]
Hey i've problem installing ruby-augeas 0.4.1 on my vagrant VM to use it with Puppet.

==Host Version==
Ruby =1.8.7
gem = 1.6.2
Vagrant = 1.0.3
Puppet = 2.7.14

==VM Version==
Lucid32 box
only one ruby installed by vagrant under /opt/vagrant-ruby
packages: augeas-tools + libaugeas-dev + lib

==Output==
vagrant@lucid32: $ sudo gem install ruby-augeas  #Also cloned this git repo and run the "$sudo rake build" but get the same error
ERROR:  Error installing ruby-augeas:
    ERROR: Failed to build gem native extension.
        /opt/vagrant_ruby/bin/ruby extconf.rb
creating Makefile
make
/usr/bin/gcc -I. -I/opt/vagrant_ruby/lib/ruby/1.8/i686-linux -I/opt/vagrant_ruby/lib/ruby/1.8/i686-linux -I. -I'/opt/vagrant_ruby/include'  -D_FILE_OFFSET_BITS=64  -fPIC -g -O2     -c _augeas.c
_augeas.c: In function 'Init__augeas':
_augeas.c:402: error: 'AUG_ENABLE_SPAN' undeclared (first use in this function)
_augeas.c:402: error: (Each undeclared identifier is reported only once
_augeas.c:402: error: for each function it appears in.)
make: **\* [_augeas.o] Error 1

**Comment by raphink** [comment]
Hello,

Which version of libaugeas-dev are you using?

**Comment by overnin** [comment]
The version of augeas's packages on the VM (with $sudo apt-cache showpkg [pkgname])
- libaugeas-dev: 0.7.0-1ubuntu1
- augeas-tools: 0.7.0-1ubuntu1 
- libaugeas0:  0.7.0-1ubuntu1

**Comment by raphink** [comment]
You need version 0.8.0 minimum in order to have `aug_span`. I'd recommend you use 0.10.0 if you're going to upgrade. You can use [my Augeas PPA](https://launchpad.net/~raphink/+archive/augeas) to install them.

**Comment by overnin** [comment]
I have updated my version to 0.10.0, but i have an new error that it cannot find libxml/tree.h but libxml2-dev (2.7.6) is installed. Any clue?

==Output==
/usr/include/augeas.h:24:25: error: libxml/tree.h: No such file or directory
In file included from _augeas.c:23:
/usr/include/augeas.h:323: error: expected declaration specifiers or '...' before 'xmlNode'
make: **\* [_augeas.o] Error 1

**Comment by raphink** [comment]
Which Ubuntu release are you using (and consequently, which version of the
package did you install)?

On Wed, Jul 25, 2012 at 12:05 PM, overnin <
reply@reply.github.com

**Comment by overnin** [comment]
I'm on the standard vagrant's virtual box Lucid32. So after adding ur ppa repo and updating, it's installing the 0.10.0 for lucid.
0.10.0-0ubuntu1~lucid1~pparaphink1 (/var/lib/apt/lists/ppa.launchpad.net_raphink_augeas_ubuntu_dists_lucid_main_binary-i386_Packages)

**Comment by raphink** [comment]
OK you're on lucid. Version 0ubuntu1 doesn't include the patch for proper
detection of the include path for libxml2.

I recently backported the 0ubuntu4 package for oneiric, but not lucid. I
will do it now. Once built, it will be available on the Augeas PPA as
version 0.10.0-0ubuntu4~lucid~pparaphink1.

On Wed, Jul 25, 2012 at 12:41 PM, overnin <
reply@reply.github.com

**Comment by overnin** [comment]
Ok thanks, i just upgrade and now the gem ruby-augeas is installing without any issue. 

Thanks a lot.
